apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dappbox-default-front
  name: dappbox-default-front
spec:
  type: LoadBalancer
  ports:
  - name: "8281"
    port: 8281
    targetPort: 8281
  selector:
    io.kompose.service: dappbox-default-front
status:
  loadBalancer: {}
