apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dappboxservice
  name: dappboxservice
spec:
  ports:
  - name: "8384"
    port: 8384
    targetPort: 8384
  - name: "22000"
    port: 22000
    targetPort: 22000
  - name: "21027"
    port: 21027
    protocol: UDP
    targetPort: 21027
  selector:
    io.kompose.service: dappboxservice
status:
  loadBalancer: {}
