apiVersion: v1
kind: ConfigMap
metadata:
  name: ethereum-config
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  networkid: "{{ .Values.geth.genesis.networkId }}"
  genesis.json: |-
    {
        "config": {
            "chainId": {{ .Values.geth.genesis.networkId }},
            "homesteadBlock": 0,
            "eip150Block": 0,
            "eip155Block": 0,
            "eip158Block": 0,
            "clique": {
              "period": 5,
              "epoch": 30000
         }
        },
        "nonce": "0x0",
        "timestamp": "0x5ba1f6ee",
        "extraData": "0x000000000000000000000000000000000000000000000000000000000000000094a7081365a9522873eb8163393b6a7e9b74f95efaf517f6a219c356a54ceed07eda7de9645ad6820000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "difficulty":  {{ .Values.geth.genesis.difficulty | quote }},
        "gasLimit": {{ .Values.geth.genesis.gasLimit | quote }},
        "alloc": {
            {{- if .Values.geth.account.address }}
            {{ .Values.geth.account.address | quote }}: {
                "balance": "1000000000000000000000000"
            }
            {{- end }}
        }
    }
